### ISSUE TITLE
checkmark should have lower opacity to show avatar behind it

### ISSUE THREAD

**Issue by rlueder** [rlueder/tidytweets#17]

**Comment by Ilnicki010** [comment]
Hey, @rlueder I'd love to take care of that and join the project, But may you provide some more detailed info on how to get everything up and going?

I mean how my .env file should look like and etc.

**Comment by rlueder** [comment]
Hey @Ilnicki010 of course, thanks for wanting to help. I was actually not expecting anyone to find it just yet, I'm working on the README updates at this very moment, it includes the details you need to get the app running locally. In the mean time I'll add you as a contributor so you can take a look around.

**Comment by rlueder** [comment]
Implemented on https://github.com/rlueder/tidytweets/pull/29
