### ISSUE TITLE
Bug: When the user's language is not in the translations, texts are broken

### ISSUE THREAD

**Issue by ColomboJuan** [rlueder/tidytweets#45]
# To reproduce
1. Change the language for one that does not have translations.
2. When you enter the app the texts are broken
![image](https://user-images.githubusercontent.com/42392347/86542039-61292d00-bee8-11ea-943e-1abb3bb9d3c5.png)

One possible solution is to add defaultMessage in FormattedMessage 
Example: 
`<FormattedMessage id="Following.unfollow--selected" defaultMessage ="Unfollow Selected" />
`

**Comment by rlueder** [comment]
`IntlProvider` takes a `defaultLocale` prop as a fallback in case of a missing translation, that prop wasn't set. I set it to "en" as a fallback.
