### ISSUE TITLE
add option to also remove suspended/inactive accounts

### ISSUE THREAD

**Issue by rlueder** [rlueder/tidytweets#9]
Some account ids don't return a response Object from the users_lookup API, (in my case approx. 200). The UI should let the user know about those and offer to unfollow those "suspended/inactive" accounts.

**Comment by ColomboJuan** [comment]
This issue is available?,Can I take this issue?

**Comment by rlueder** [comment]
@juan-colombo95 yep, still available, it does need a little research first though, some background info below:

When I first started working with the Twitter APIs I noticed that the response I get from `utils/getFriendsInfo` doesn't match the total number of JSON Objects I get from `utils/getFriendsIds`.

If you look at the `Dashboard` and `Following` components you'll see I have the `SUSPENDED` constant and also a section commented out for "suspended" accounts. The `suspended` prop is the difference between all the accounts a user follows and the accounts that actually return a JSON Object from the API:

```
const SUSPENDED = difference(
  friends.ids,
  friends.data.map((item) => item.id)
);
```
If I log `SUSPENDED` to the console I can see that for my account it's an array with 147 ids. I know that Twitter might suspend accounts that have been used for spam, users might delete their accounts, etc. So the first step is to make sure that's actually valid, I haven't for example tried to unfollow those ids that returned no JSON response.

Let me know if you need any more details.

Some Twitter docs on suspended accounts: https://help.twitter.com/en/managing-your-account/locked-and-limited-accounts

**Comment by rlueder** [comment]
This command line tool developed by the Twitter team might be helpful when testing different endpoints: https://github.com/twitter/twurl

**Comment by rlueder** [comment]
I created a post on the Twitter developer forum, hopefully someone from their team will have some insight:
https://twittercommunity.com/t/pull-user-details-with-id-error/11974

**Comment by rlueder** [comment]
Closing as this is not supported by API see last comment in link above. We can instead highlight the total number of accounts that didn't return any details (already in code but commented out).
